services:
  postgres:
    image: postgres:17
    container_name: sanctum_db
    environment:
      POSTGRES_DB: sanctum
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: